---
title: "R Notebook"
output: html_notebook
---

#Import tables
```{r}
setwd("/Users/karlavasco/OneDrive\ -\ Michigan\ State\ University/Zhang_lab/Mila_project/tables/smartchip")

library(readxl)
#read in otu table (smartchip normalized abundance)
otu_table <- read_excel("smartchip_phyloseq_tables.xlsx", sheet = "abundance")

library(dplyr)
#converting the abundance table to matrix (required to merge with taxonomy table)
otu_table <- otu_table %>% remove_rownames %>% column_to_rownames(var="GENE_ID") 
otu_table=as.matrix(otu_table,rownames=TRUE)

#multiplying abundance by 10^9 so we can calculate diversity measures (it won't be possible with decimals)
otu_table <- otu_table*10^9
mode(otu_table) <- "integer"

#converting empty values to 0 (in case they exist)
otu_table[is.na(otu_table)] <- 0

#read in taxonomy (gene ID for smartchip)
taxonomy <- read_excel("smartchip_phyloseq_tables.xlsx", sheet = "gene_ID")

#setting taxonomy row_names for GENE_ID (that will enable merging with the abundance table)
taxonomy <- taxonomy %>% remove_rownames %>% column_to_rownames(var="GENE_ID")
taxonomy=as.matrix(taxonomy)

#read in metadata
metadata <- read_excel("smartchip_phyloseq_tables.xlsx", sheet = "metadata")

#setting metadata row_names for sample ID (that will enable merging with the other tables)
metadata <- metadata %>% remove_rownames %>% column_to_rownames(var="Sample_ID")

#Changing the levels of source and group to make them better organized in the plots
metadata <- metadata %>% mutate(Source = fct_relevel(Source,"Meconium","Infant 7 days", "Mother"))
metadata <- metadata %>% mutate(Group = fct_relevel(Group,"Control","Sepsis"))

library("phyloseq")

#import all tables as phyloseq objects
OTU = otu_table(otu_table,taxa_are_rows=TRUE)
TAX = tax_table(taxonomy)
META = sample_data(metadata)

# Sanity checks for consistent OTU names
taxa_names(TAX)
taxa_names(OTU)

# Same sample names
sample_names(OTU)
sample_names(META)

#Making phyloseq object
physeq=phyloseq(OTU,TAX,META)
```

#Heat-tree
#Modifying phyloseq object
```{r}
#To plot the tolal counts as percentage in the heat tree, divide the sum of the counts by the number of samples and multiply by 100. Here, we have 376 samples.

physeq_t  = transform_sample_counts(physeq, function(x) x / sum(x)/376*100 ) 

#Filter all the taxa that have a percentage higher than 0.0001. This is optional, but I prefer to plot the most abundant genes

physeq_t1 = phyloseq::filter_taxa(physeq_t, function(x) mean(x) > 1e-5, TRUE)
physeq_t1 <-  physeq_t1 %>% subset_taxa(Type %in% "ARG")
```

#Metacoder
```{r}
library(metacoder)

#transforming physeq object into a metacoder object

metacoder_object = parse_phyloseq(physeq_t1) 

#creating a column with total counts. Keep as is
metacoder_object$data$taxon_counts <- calc_taxon_abund(metacoder_object, data = "otu_table") 

metacoder_object$data$taxon_counts$total <- rowSums(metacoder_object$data$taxon_counts[, -1]) # -1 = taxon_id column

metacoder_object$data$taxon_prop <- calc_obs_props(metacoder_object, "otu_table")
```
#Heat tree
```{r}
#Plotting heat-tree

heat_tree = metacoder_object %>%
  heat_tree(node_label = taxon_names,
            node_size = metacoder_object$data$taxon_counts$total,
             node_size_range = c(0.01, 0.06),
            edge_size_range = c(0.005, 0.005),
            node_label_size_range = c(0.01, 0.05),
         node_color = metacoder_object$data$taxon_counts$total,

            node_color_axis_label = "Proportion",
            node_size_axis_label = "ARG count",
            overlap_avoidance =1) #Modify if necessary
heat_tree
```

```{r}
setwd("~/OneDrive\ -\ Michigan\ State\ University/Zhang_lab/Mila_project/figures/smartchip") 

library(ggplot2)
ggsave(plot = heat_tree, "heat-tree_ARGs.png", height = 9, width = 11)
```

#Modifying phyloseq object
```{r}
#To plot the tolal counts as percentage in the heat tree, divide the sum of the counts by the number of samples and multiply by 100. Here, we have 376 samples.

physeq_t  = transform_sample_counts(physeq, function(x) x / sum(x)/376*100 ) 

#Filter all the taxa that have a percentage higher than 0.0001. This is optional, but I prefer to plot the most abundant genes

physeq_t1 = phyloseq::filter_taxa(physeq_t, function(x) mean(x) > 1e-5, TRUE)
physeq_t1 <-  physeq_t1 %>% subset_taxa(Type %in% "MGE")
```

#Metacoder
```{r}
library(metacoder)

#transforming physeq object into a metacoder object

metacoder_object = parse_phyloseq(physeq_t1) 

#creating a column with total counts. Keep as is
metacoder_object$data$taxon_counts <- calc_taxon_abund(metacoder_object, data = "otu_table") 

metacoder_object$data$taxon_counts$total <- rowSums(metacoder_object$data$taxon_counts[, -1]) # -1 = taxon_id column

metacoder_object$data$taxon_prop <- calc_obs_props(metacoder_object, "otu_table")
```
#Heat tree
```{r}
#Plotting heat-tree

heat_tree = metacoder_object %>%
  # subset to the class rank
  heat_tree(node_label = taxon_names,
            node_size = metacoder_object$data$taxon_counts$total,
             node_size_range = c(0.01, 0.06),
            edge_size_range = c(0.005, 0.005),
            node_label_size_range = c(0.01, 0.05),
         node_color = metacoder_object$data$taxon_counts$total,

            node_color_axis_label = "Proportion",
            node_size_axis_label = "MGE count",
            overlap_avoidance =1) #Modify if necssary
heat_tree
```

```{r}
setwd("~/OneDrive\ -\ Michigan\ State\ University/Zhang_lab/Mila_project/figures/smartchip") 

library(ggplot2)
ggsave(plot = heat_tree, "heat-tree_MGEs.png", height = 9, width = 11)
```